<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-8TP6OQIJ" failures="1" tests="4" name="Test" time="21.898" errors="0" timestamp="2024-05-17T10:15:24 IST">
  <testcase classname="testcases.registerTestCases" name="verifyRegisterationWithValidData" time="1.949"/>
  <testcase classname="testcases.registerTestCases" name="verifyRegisterationWithBlankData" time="0.855"/>
  <testcase classname="testcases.loginTestCases" name="verifyLoginWithInValidData" time="1.186">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Warning: No match for E-Mail Address and/or Password.] but found [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.]
at resources.commonMethods.handleAssertion(commonMethods.java:17)
at testcases.loginTestCases.verifyLoginWithInValidData(loginTestCases.java:71)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginWithInValidData -->
  <testcase classname="testcases.loginTestCases" name="verifyLoginWithValidData" time="1.605"/>
  <testcase classname="resources.baseClass" name="@BeforeSuite ExtentReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite ExtentReport -->
  <testcase classname="resources.baseClass" name="@AfterSuite endReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite endReport -->
  <testcase classname="testcases.registerTestCases" name="verifyRegisterationWithInvalidData" time="0.0">
    <ignored/>
  </testcase> <!-- verifyRegisterationWithInvalidData -->
</testsuite> <!-- Test -->
